[build]
  command = ""
  publish = "frontend/dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
